apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: turbosaurio/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always
        ports: 
          - containerPort: 3000
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_BUCKET

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 3000
  selector:
    service: reverseproxy
  type: LoadBalancer

